let tenisJson = [
    {id:1, name:'VANS AUTHENTIC', images: ['images/tenis1.png','images/tenis1--2.png','images/tenis1--3.png','images/tenis1--4.png'], price:249, sizes:['38', '39', '40', '41', '42'], description:'O tênis "Vans Authentic" combina o estilo cano baixo original e agora icônico da marca com um cabedal de lona resistente.'},
    {id:2, name:'BAW CLOTHING SESSION WHITE X LILAC', images: ['images/tenis2.png', 'images/tenis2.png', 'images/tenis2.png', 'iimages/tenis2.png'], price:359.90, sizes:['35', '36', '38', '39', '40'], description:'Com o "The Session" você garante conforto e uma peça que dará uma ao seu look uma nova cara!'},
    {id:3, name:'NIKE SB CHRON 2', images:['images/tenis3.png', 'images/tenis3--2.png', 'images/tenis3--3.png', 'images/tenis3.png'], price:269.99, sizes:['38', '39', '40', '41', '44'], description:'Os tênis "Nike SB Check", de lona para skate são projetados com um toque natural e confortável.'},
    {id:4, name:'CHINELO ADILETTE 22', images:['images/tenis4.png', 'images/tenis4--2.png', 'images/tenis4--3.png', 'images/tenis4--4.png'], price:299.99, sizes:['35', '37', '38', '40', '43'], description:'Este chinelo adidas "Adilette" é uma resposta à pergunta: "Como seria usar chinelos no espaço?" Inspirado na topografia 3D e nas expedições humanas a Marte, ele desafia a gravidade com detalhes futuristas.'},
    {id:5, name:'NIKE BLAZER MID 77 VINTAGE', images:['images/tenis5.png', 'images/tenis5--2.png', 'images/tenis5--3.png', 'images/tenis5--4.png'], price:749.99, sizes:['38', '39', '40', '41', '42'], description:'"Blazer Mid 77 SE", com um design atemporal, estilo dos anos 70, amado na década de 80 e clássico dos anos 90.'},
    {id:6, name:'DUNK LOW MINERAL CLAY', images:['images/tenis6.png', 'images/tenis6--2.png', 'images/tenis6--3.png', 'images/tenis6--4.png'], price:899.99, sizes:['38', '40', '41', '43', '44'], description:'Construído para conforto e projetado para fazer uma declaração, o "Dunk Low Disrupt 2" permite que você transforme qualquer rua em seu palco.'},
    {id:7, name:'4D FUSIO', images:['images/tenis7.png', 'images/tenis7--2.png', 'images/tenis7--3.png', 'images/tenis7--4.png'], price:799.99, sizes:['35', '36', '38', '39', '40'], description:'A vida muda rapidamente. Não podemos prever o futuro, mas podemos caminhar em direção a ele com confiança. Calce este tênis inspirado na corrida e comece a jornada'},
    {id:8, name:'FORUM LOW HEBRU BRANTLEY', images:['images/tenis8.png', 'images/tenis8--2.png', 'images/tenis8--3.png', 'images/tenis8--4.png'], price:899.99, sizes:['39', '40', '41', '42', '45'], description:'Onde você está não é onde você precisa ficar. Quebre as barreiras: esta é a ideia capturada neste tênis "adidas x Hebru Brantley."'},
    {id:9, name:'OFF-NOIR AND SUMMIT WHITE', images:['images/tenis9.png', 'images/tenis9--2.png', 'images/tenis9--3.png', 'images/tenis9--4.png'], price:1399.99, sizes:['36', '38', '39', '40', '42'], description:'Não há nada mais clássico do que um 97 em preto e branco. Entre no Air Max 97 Terrascape em "Off Noir e Summit White."'}
];